[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 112, lines = 30 }
padding = { x = 8, y = 8 }
decorations_theme_variant = "Dark"
resize_increments = true

[font]
normal = { family = "Iosevka Term", style = "Medium Extended" }
bold = { style = "Bold Extended" }
bold_italic = { style = "Bold Extended Italic" }

[cursor]
style = { blinking = "On" }
