{
  config,
  pkgs,
  ...
}: {
  imports = [
    ./programs/bat.nix
    ./programs/delta.nix
    ./programs/git.nix
    ./programs/neovim.nix
    ./programs/shell.nix
    ./programs/starship.nix
    ./programs/tlrc.nix
  ];

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "25.11"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  home.packages = with pkgs; [
    tmux
    fd
    fastfetch
    eza
    btop
    lesspipe
  ];

  # Application configs are generated by the imported program modules, except tmux.
  # Other static .config files remain in the repository as manual backups.
  # Helper scripts and external tool-manager files are still deployed directly.
  home.file = {
    "${config.xdg.configHome}/nixpkgs/config.nix".source = ./nixpkgs-config.nix;
    "${config.xdg.configHome}/tmux/tmux.conf".source = .config/tmux/tmux.conf;
    "${config.xdg.dataHome}/zsh/fzf-preview.zsh".source = .local/share/zsh/fzf-preview.zsh;
    "${config.xdg.dataHome}/zsh/zstyle.zsh".source = .local/share/zsh/zstyle.zsh;
    ".local/bin/fzf-preview-all".source = .local/bin/fzf-preview-all;
    ".zimrc".source = ./.zimrc;
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. These will be explicitly sourced when using a
  # shell provided by Home Manager. If you don't want to manage your shell
  # through Home Manager then you have to manually source 'hm-session-vars.sh'
  # located at either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/roberth/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    # EDITOR = "emacs";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # Packages overrides in favour of system packages
  #programs.alacritty.package = pkgs.emptyDirectory;

  # Hide home-manager news notification https://github.com/nix-community/home-manager/issues/2033
  news.display = "silent";

  nix.gc.automatic = true;
  nix.gc.options = "--delete-older-than 3d";
  nixpkgs.config = import ./nixpkgs-config.nix;
}
