import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/custom.toml",
]

[window]
dimensions = { columns = 112, lines = 30 }
padding = { x = 8, y = 8 }
decorations_theme_variant = "Dark"
resize_increments = true

[cursor]
style = { blinking = "On" }
